name: Release
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
      - alpha
      - beta
jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn add -D semantic-release @semantic-release/exec

      - name: Create Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run: npx semantic-release

  deploy:
    needs: semver
    runs-on: ubuntu-latest
    if: needs.semver.outputs.version != '' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Add new release env
        run: echo ${{ needs.semver.outputs.version }} | vercel env add NEXT_PUBLIC_SENTRY_RELEASE production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Trigger Deploy
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_OppuEhwfzRLkFhlBfT7lTgo4j8eg/TPoo064nXF
